package functionality;

public enum Event {
    ARRIVE_OF_PASSENGER,
    BOUGHT_TICKET,
    PASSENGER_GOING_TO_PLANE,
    STEWARDESS_GOING_TO_PLANE,
    GOING_TO_TRAIN,
    TAKE_OFF,
    DEFAULT_FIRST_STEWARDESS_PLACE,
    DEFAULT_SECOND_STEWARDESS_PLACE,
    DEFAULT_THIRD_STEWARDESS_PLACE,
    DEFAULT_CHECK_IN_PLACE,
    DEFAULT_TRAIN_PLACE,
    DEFAULT_PLANE_PLACE
}
